// <auto-generated />
using System;
using CommunicationProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunicationProject.Migrations
{
    [DbContext(typeof(CommunicationDbContext))]
    [Migration("20260805065334_extendsiteidlength1")]
    partial class extendsiteidlength1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommunicationProject.Models.CommunicationLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConnectedLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("LinkTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SiteFromId")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("SiteToId")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedLinkId")
                        .IsUnique()
                        .HasFilter("[ConnectedLinkId] IS NOT NULL");

                    b.HasIndex("SiteFromId");

                    b.HasIndex("SiteToId");

                    b.HasIndex("Name", "IsPrimary")
                        .IsUnique();

                    b.HasIndex("LinkTypeId", "SiteFromId", "SiteToId")
                        .IsUnique();

                    b.ToTable("CommunicationLinks");
                });

            modelBuilder.Entity("CommunicationProject.Models.E1", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConnectedE1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("E1Number")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<Guid?>("JoinE1Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PathId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PathOrder")
                        .HasColumnType("int");

                    b.Property<Guid>("StmId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedE1Id")
                        .IsUnique()
                        .HasFilter("[ConnectedE1Id] IS NOT NULL");

                    b.HasIndex("PathId", "PathOrder")
                        .IsUnique()
                        .HasFilter("[PathId] IS NOT NULL AND [PathOrder] IS NOT NULL");

                    b.HasIndex("StmId", "E1Number")
                        .IsUnique();

                    b.ToTable("E1s");
                });

            modelBuilder.Entity("CommunicationProject.Models.LinkType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LinkTypes");
                });

            modelBuilder.Entity("CommunicationProject.Models.Site", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("CommunicationProject.Models.Stm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConnectedStmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectedStmId")
                        .IsUnique()
                        .HasFilter("[ConnectedStmId] IS NOT NULL");

                    b.HasIndex("LinkId", "Number")
                        .IsUnique();

                    b.ToTable("Stms");
                });

            modelBuilder.Entity("CommunicationProject.Models.CommunicationLink", b =>
                {
                    b.HasOne("CommunicationProject.Models.CommunicationLink", "ConnectedLink")
                        .WithOne()
                        .HasForeignKey("CommunicationProject.Models.CommunicationLink", "ConnectedLinkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommunicationProject.Models.LinkType", "LinkType")
                        .WithMany("Links")
                        .HasForeignKey("LinkTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationProject.Models.Site", "SiteFrom")
                        .WithMany("LinksFrom")
                        .HasForeignKey("SiteFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CommunicationProject.Models.Site", "SiteTo")
                        .WithMany("LinksTo")
                        .HasForeignKey("SiteToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectedLink");

                    b.Navigation("LinkType");

                    b.Navigation("SiteFrom");

                    b.Navigation("SiteTo");
                });

            modelBuilder.Entity("CommunicationProject.Models.E1", b =>
                {
                    b.HasOne("CommunicationProject.Models.E1", "ConnectedE1")
                        .WithOne()
                        .HasForeignKey("CommunicationProject.Models.E1", "ConnectedE1Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommunicationProject.Models.Stm", "Stm")
                        .WithMany("E1Channels")
                        .HasForeignKey("StmId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectedE1");

                    b.Navigation("Stm");
                });

            modelBuilder.Entity("CommunicationProject.Models.Stm", b =>
                {
                    b.HasOne("CommunicationProject.Models.Stm", "ConnectedStm")
                        .WithOne()
                        .HasForeignKey("CommunicationProject.Models.Stm", "ConnectedStmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CommunicationProject.Models.CommunicationLink", "Link")
                        .WithMany("Stms")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConnectedStm");

                    b.Navigation("Link");
                });

            modelBuilder.Entity("CommunicationProject.Models.CommunicationLink", b =>
                {
                    b.Navigation("Stms");
                });

            modelBuilder.Entity("CommunicationProject.Models.LinkType", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("CommunicationProject.Models.Site", b =>
                {
                    b.Navigation("LinksFrom");

                    b.Navigation("LinksTo");
                });

            modelBuilder.Entity("CommunicationProject.Models.Stm", b =>
                {
                    b.Navigation("E1Channels");
                });
#pragma warning restore 612, 618
        }
    }
}
